// eslint-disable-next-line no-undef
define([], function () {
  return {
    NewCustomer: "New Customer",
  PropertyPaneDescription: "Description",
  DescriptionFieldLabel: "Description",
  BasicGroupName: "Group Name",
    LoadingText: "Loading...",
    WorkingOnIt: "Working on it...",
    Save: "Save",
    Cancel: "Cancel",
    RequiredValidationMessage: "This field is required",
    NegativeNumberValidationMessage: "Value must be a positive number",
    Filter: "Filter",
    Sort: "Sort",
    Refresh: "Refresh",
    Submit: "Submit",
    Clear: "Clear",
    NoItemsFound: "No items found",
    Add: "New",
    Update: "Update",
    Delete: "Delete",
    StartDate: "Request Start Date",
    EndDate: "Request End Date",
    StartWorkflow: "Start Workflow",
    Print: "Print",
    PrintPreview: "Print Preview",
    AddTask: "Add Task",
    FileName: "File Name",
    Send: "Send",
    View: "View",
    Stock: {
      Title: "Item",
      Description: "Description",
      StockQuantity: "Stock Quantity",
      UnitPrice: "Unit Price",
      ItemCategory: "Item Category",
      Currency: "Currency",
      Id : "Item ID",  
    },
    Customer: {
    Id: "Customer ID",
    Title: "Customer Name",
    PhoneNumber: "Phone Number",
    Created: "Created",
    CustomerType: "Customer Type",
    TotalOrders: "Total Orders",
    Modified: "Modified",
    Description: "Description",
    
  },
    Order: {
      Title: "Order ID",
    Id: "ID",
    Item: "Item",
    QuantityOrdered: "Quantity",
    UnitPrice: "Unit Price",
    TotalPrice: "Total Price",
    OrderDate: "Order Date",
    Currency: "Currency",
    OrderStatus: "Order Status",
    Customer: "Customer",
    Created: "Created",
    TotalOrders: "Total Orders",
    Modified: "Modified",
    Description: "Description",
    NewOrder: "New Order"
    },
    PropertyPane: {
      Description: "Configure the web part",
      BasicGroupName: "Settings",
      FlowUrlFieldLabel: "Power Automate Flow URL"
    },
    
  }
});